# Generated by Django 3.2.6 on 2021-08-30 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0003_auto_20210830_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Product',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='staff',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
